- name: Ubuntu Setup
  hosts: local
  become: yes
  tasks:
    - name: Build requirements
      ansible.builtin.apt:
        name:
          - vim-nox
          - git
          - curl
          - fuse
          - xclip
          - stow
          - zsh
          - make
          - build-essential
          - software-properties-common
        state: present
        update_cache: yes
    - name: Python requirements
      ansible.builtin.apt:
        name:
          - libbz2-dev
          - libffi-dev
          - liblzma-dev
          - libncursesw5-dev
          - libreadline-dev
          - libsqlite3-dev
          - libssl-dev
          - libxml2-dev
          - libxmlsec1-dev
          - tk-dev
          - xz-utils
          - zlib1g-dev
        state: present
