Output tmp/zellij.png
Set Shell zsh
Set FontSize 28
Set Width 2400
Set Height 1200
Set Theme "Catppuccin Mocha"

Type "zellij -s zellij-test"
Enter
Sleep 2s

Ctrl+a
Type "%"
Sleep 500ms

Ctrl+a
Type "%"
Sleep 500ms

Ctrl+a
Type " "
Sleep 500ms

Ctrl+a
Type " "
Sleep 500ms

Ctrl+a
Type " "
Sleep 500ms

Ctrl+a
Type " "
Sleep 500ms

Ctrl+a
Type " "
Sleep 500ms

Ctrl+a
Type " "
Sleep 500ms

Screenshot tmp/zellij.png

Type "exit"
Enter
Sleep 300ms
Type "exit"
Enter
Sleep 300ms
Type "exit"
Enter
Sleep 500ms
